services:
  postgres-bolao:
    image: postgres:15
    container_name: db-bolao-copa
    restart: always
    environment:
      POSTGRES_DB: bolao_empresa
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - pg_bolao_data:/var/lib/postgresql/data

volumes:
  pg_bolao_data: